language: r
r:
  - release
  - devel
sudo: false
cache: packages

r_packages:
  - knitr
  - devtools
  - methods

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - yi.yang6@mcgill.ca
    - sahir.bhatnagar@gmail.com
